In [17]:
import pandas as pd

SOE_MAJORS = ["EAT", "EDX", "EMR", "EMQ", "ETH", "ECH", "EBA", "ESJ", "PES", "EAD", "EDL", "EAH", "ETE", "EIS", "ELY", "EDN", "EBI", "EAF", "EAJ", "EBB", "ETN", "EAB", "EAV", "ECK", "EAM", "EEC", "EMD", "EMH", "EMJ"]

soe = pd.read_csv("soe-fall-22.csv")
display(soe.columns)
soe

Index(['Student Id', 'Last', 'Cur Term Desc', 'School Desc', 'Major 1',
       'Major 1 Desc', 'Program', 'Major 2', 'Major 2 Desc', 'Cred Ungraded ',
       'Cstep Flag ', 'Step Program'],
      dtype='object')

,Student Id,Last,Cur Term Desc,School Desc,Major 1,Major 1 Desc,Program,Major 2,Major 2 Desc,Cred Ungraded,Cstep Flag,Step Program
0,1901115,MATASSA,Fall 2022,College of Arts and Sciences,ENG,ENGLISH,12,NaN,NaN,14.0,NaN,SSE
1,1840714,PUGH,Fall 2022,College of Arts and Sciences,HIS,HISTORY,12,NaN,NaN,18.0,NaN,SSE
2,1901185,NICOLAOU,Fall 2022,College of Arts and Sciences,HIS,HISTORY,12,NaN,NaN,14.0,NaN,SEE
3,1778328,HALL,Fall 2022,College of Arts and Sciences,SOC,SOCIOLOGY,12,NaN,NaN,16.0,NaN,SEE
4,1918703,EASTERLING,Fall 2022,College of Arts and Sciences,ENG,ENGLISH,12,NaN,NaN,16.0,NaN,SSE
...,...,...,...,...,...,...,...,...,...,...,...,...
701,1614803,WROBLEWSKI,Fall 2022,Ruth S. Ammon College of Education and Health ...,ETE,TEACH ENG SPKRS OTHER LANGUAGE,85,NaN,NaN,3.0,NaN,NaN
702,1896479,MURDOLO,Fall 2022,Ruth S. Ammon College of Education and Health ...,EAH,TCHNG STDS W/DISABILITIES 7-12,84,NaN,NaN,9.0,NaN,NaN
703,1894845,CASTILLO,Fall 2022,Ruth S. Ammon College of Education and Health ...,EBI,BIL CHLD SPEC ED INCLUSIVE ST,84,NaN,NaN,12.0,NaN,NaN
704,1921633,REYES,Fall 2022,Ruth S. Ammon College of Education and Health ...,EDN,EDUCATION NON-DEGREE,84,NaN,NaN,12.0,NaN,NaN
705,1923261,CHIEN,Fall 2022,Ruth S. Ammon College of Education and Health ...,EDX,EDUCATIONAL TECHNOLOGY,84,NaN,NaN,3.0,NaN,NaN

In [16]:
# figure out how STEP works
soe["Step Program"].unique()

array(['SSE', 'SEE', 'SET', 'SCE', 'SAE', nan], dtype=object)

In [20]:
step = soe[soe["Step Program"].notnull()]

# show all of the majors and step codes to try to understand them

step[['Step Program','Major 1 Desc']].drop_duplicates()

# this is an outlier -- and she's in my program!
step[step["Major 1"].isin(SOE_MAJORS)]

In [21]:
step.groupby("Step Program")["Student Id"].count()

Step Program
SAE      1
SCE      1
SEE    207
SET      2
SSE    170
Name: Student Id, dtype: int64